spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    type-aliases-package: bhboot.model
    mapper-locations:
    - classpath:/mapper/*Mapper.xml
#    type-handlers-package: bhboot.mapper.*